# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

a = 2
num = int(4E6)
Fibonacci_seq = [1]
Fibonacci_seq_even = []

# find Fibonacci sequence until a certain number
while a < num:
    Fibonacci_seq.append(a)
    a = a + Fibonacci_seq[-2]

# find even numbers in Fibonacci sequence
for b in Fibonacci_seq:
    if b % 2 == 0:
        Fibonacci_seq_even.append(b)

# find sum of even number in Fibonacci sequence
Fibonacci_sum_even = sum(Fibonacci_seq_even)

print("The sum of the even-valued terms in the Fibonacci sequence below {} is {}." .format(num, Fibonacci_sum_even))
